### ISSUE TITLE
Command> custom channels

### ISSUE THREAD

**Issue by yJulian** [ypsilondev/butterbrotbot#1]
Create custom channels with a command with or without limited user count.
They should be deleted after the channel is empty for a few seconds.

Presets for games:
* Schach (2 Personen)

**Comment by Gregyyy** [comment]
I would suggest deleting the channel after 1 minute. This is enough time to rejoing if your internet got disconnected.

**Comment by Gregyyy** [comment]
Added feature with pull request #2
