### ISSUE TITLE
Verification with educational email addr

### ISSUE THREAD

**Issue by yJulian** [ypsilondev/butterbrotbot#9]
Add a role that can only be got by linking an educational email address with the discord account.
This should be voluntary but should give users access to hidden channels with others

**Comment by DeveloperTK** [comment]
My naive approach for checking the validity of the provided email adress would look something like this:

    /u[a-z]{4}@student\.kit\.edu/

**Comment by yJulian** [comment]
> For maximum security, the codes should be stored with a reference to the user in the memory and without one in a database so that duplicates can be avoided.

The security is a upside yeah. But remember a power-outage or glitch in bot could lead in a automatic restart of the docker container. Or something like a buggy discord API with resulting timeout could lead to a flush of the references due to the linked restart of the bot.

**Comment by Shirkanesi** [comment]
> 
> 
> > For maximum security, the codes should be stored with a reference to the user in the memory and without one in a database so that duplicates can be avoided.
> 
> The security is a upside yeah. But remember a power-outage or glitch in bot could lead in a automatic restart of the docker container. Or something like a buggy discord API with resulting timeout could lead to a flush of the references due to the linked restart of the bot.

What about just using a hash with a Salt stored in settings.yml? ==> No need to store the secret key on the DB beacause it can be generated on the fly :)

**Comment by yJulian** [comment]
We could also use field level encryption from mongodb...
But i think it wouldnt be that big of a security concern to store the keys even in plain text in the database.
Because what should an attacher do with the tokens? Verify a bug user?
But the hash with salt could be a great idear when it comes to  work against benefit
